<a href="https://colab.research.google.com/github/YousefBarty/ML-Projects/blob/main/brain_stroke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import  StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.linear_model import Perceptron , SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline  import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score, recall_score, precision_score, roc_auc_score

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/brain_stroke.csv')

In [ ]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [ ]:
df['smoking_status'].value_counts()

never smoked       1838
Unknown            1500
formerly smoked     867
smokes              776
Name: smoking_status, dtype: int64

In [ ]:
df['smoking_status'] = df['smoking_status'].replace(['Unknown'], ['never smoked'])

In [ ]:
df['smoking_status'].value_counts()

never smoked       3338
formerly smoked     867
smokes              776
Name: smoking_status, dtype: int64

In [ ]:
df.shape

(4981, 11)

In [ ]:
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [ ]:
categorical = df.select_dtypes(include='object')
categorical

gender ever_married      work_type Residence_type   smoking_status
0       Male          Yes        Private          Urban  formerly smoked
1       Male          Yes        Private          Rural     never smoked
2     Female          Yes        Private          Urban           smokes
3     Female          Yes  Self-employed          Rural     never smoked
4       Male          Yes        Private          Urban  formerly smoked
...      ...          ...            ...            ...              ...
4976    Male           No        Private          Rural  formerly smoked
4977    Male          Yes        Private          Urban           smokes
4978  Female          Yes       Govt_job          Rural           smokes
4979    Male          Yes        Private          Rural           smokes
4980  Female          Yes        Private          Urban     never smoked

[4981 rows x 5 columns]

In [ ]:
df = pd.get_dummies(df, columns=[col for col in df.columns if col in categorical])
df.head()

age  hypertension  heart_disease  avg_glucose_level   bmi  stroke  \
0  67.0             0              1             228.69  36.6       1   
1  80.0             0              1             105.92  32.5       1   
2  49.0             0              0             171.23  34.4       1   
3  79.0             1              0             174.12  24.0       1   
4  81.0             0              0             186.21  29.0       1   

   gender_Female  gender_Male  ever_married_No  ever_married_Yes  \
0              0            1                0                 1   
1              0            1                0                 1   
2              1            0                0                 1   
3              1            0                0                 1   
4              0            1                0                 1   

   work_type_Govt_job  work_type_Private  work_type_Self-employed  \
0                   0                  1                        0   
1                   0                  1                        0   
2                   0                  1                        0   
3                   0                  0                        1   
4                   0                  1                        0   

   work_type_children  Residence_type_Rural  Residence_type_Urban  \
0                   0                     0                     1   
1                   0                     1                     0   
2                   0                     0                     1   
3                   0                     1                     0   
4                   0                     0                     1   

   smoking_status_formerly smoked  smoking_status_never smoked  \
0                               1                            0   
1                               0                            1   
2                               0                            0   
3                               0                            1   
4                               1                            0   

   smoking_status_smokes  
0                      0  
1                      0  
2                      1  
3                      0  
4                      0

In [ ]:
y = df.stroke
x = df.drop('stroke', axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.3,random_state = 0,stratify=y)

In [ ]:
x_train.shape

(3486, 18)

In [ ]:
y_train.value_counts()

0    3312
1     174
Name: stroke, dtype: int64

#### StandardScaler

In [ ]:
scaler = StandardScaler() 
scaler.fit(x_train) 
x_train = scaler.transform(x_train) 
x_test=scaler.transform(x_test)

In [ ]:
def LogisticRegressionFUN(x_train,y_train,x_test,y_test):
  lr = LogisticRegression(max_iter=1000)
  lr.fit(x_train,y_train)
  y_pred = lr.predict(x_test)
  y_probas = lr.predict_proba(x_test)
  confmat = confusion_matrix(y_test, y_pred, labels=[1,0])
  tp, fp, fn, tn = confmat.ravel()
  print(confmat)
  print("true positive", tp)
  print("false positive", fp)
  print("false negative", fn)
  print("true negative", tn)
  print('recall: ', recall_score(y_test, y_pred))
  print('precision: ', precision_score(y_test, y_pred))
  print('f1_score: ', f1_score(y_test, y_pred))
  print('auc: ', roc_auc_score(y_test, y_pred))

In [ ]:
def svmFUN(x_train,y_train,x_test,y_test):

  svc=SVC(kernel='linear',C=0.1)
  svc.fit(x_train,y_train)
  y_pred = svc.predict(x_test)
  confmat = confusion_matrix(y_test, y_pred, labels=[1,0])
  tp, fp, fn, tn = confmat.ravel()
  print(confmat)
  print("true positive", tp)
  print("false positive", fp)
  print("false negative", fn)
  print("true negative", tn)
  print('recall: ', recall_score(y_test, y_pred))
  print('precision: ', precision_score(y_test, y_pred))
  print('f1_score: ', f1_score(y_test, y_pred))
  print('auc: ', roc_auc_score(y_test, y_pred))

In [ ]:
def kN(x_train,y_train,x_test,y_test):

  knn=KNeighborsClassifier(n_neighbors=15)
  knn.fit(x_train,y_train)
  y_pred = knn.predict(x_test)
  confmat = confusion_matrix(y_test, y_pred, labels=[1,0])
  tp, fp, fn, tn = confmat.ravel()
  print(confmat)
  print("true positive", tp)
  print("false positive", fp)
  print("false negative", fn)
  print("true negative", tn)
  print('recall: ', recall_score(y_test, y_pred))
  print('precision: ', precision_score(y_test, y_pred))
  print('f1_score: ', f1_score(y_test, y_pred))
  print('auc: ', roc_auc_score(y_test, y_pred))

In [ ]:
def rF(x_train,y_train,x_test,y_test):
  rnc=RandomForestClassifier(n_estimators=15,max_depth=5)
  rnc.fit(x_train,y_train)
  y_pred= rnc.predict(x_test)
  confmat = confusion_matrix(y_test, y_pred, labels=[1,0])
  tp, fp, fn, tn = confmat.ravel()
  print(confmat)
  print("true positive", tp)
  print("false positive", fp)
  print("false negative", fn)
  print("true negative", tn)
  print('recall: ', recall_score(y_test, y_pred))
  print('precision: ', precision_score(y_test, y_pred))
  print('f1_score: ', f1_score(y_test, y_pred))
  print('auc: ', roc_auc_score(y_test, y_pred))

## RandomOverSampler

In [ ]:
from imblearn.over_sampling import RandomOverSampler

oversample = RandomOverSampler(random_state=42)

x_train_over, y_train_over = oversample.fit_resample(x_train, y_train)

In [ ]:
LogisticRegressionFUN(x_train_over, y_train_over,x_test,y_test)

[[  55   19]
 [ 373 1048]]
true positive 55
false positive 19
false negative 373
true negative 1048
recall:  0.7432432432432432
precision:  0.12850467289719625
f1_score:  0.21912350597609562
auc:  0.7403760199326702


In [ ]:
svmFUN(x_train_over, y_train_over,x_test,y_test)

[[  57   17]
 [ 391 1030]]
true positive 57
false positive 17
false negative 391
true negative 1030
recall:  0.7702702702702703
precision:  0.12723214285714285
f1_score:  0.2183908045977011
auc:  0.747555965536261


In [ ]:
kN(x_train_over, y_train_over,x_test,y_test)

[[  36   38]
 [ 353 1068]]
true positive 36
false positive 38
false negative 353
true negative 1068
recall:  0.4864864864864865
precision:  0.09254498714652956
f1_score:  0.15550755939524835
auc:  0.6190349392319835


In [ ]:
rF(x_train_over, y_train_over,x_test,y_test)

[[  53   21]
 [ 393 1028]]
true positive 53
false positive 21
false negative 393
true negative 1028
recall:  0.7162162162162162
precision:  0.11883408071748879
f1_score:  0.20384615384615384
auc:  0.719825208741465


In [ ]:
from imblearn.under_sampling import RandomUnderSampler

undersample = RandomUnderSampler(random_state=42)

x_train_under, y_train_under = undersample.fit_resample(x_train, y_train)

In [ ]:
LogisticRegressionFUN(x_train_under, y_train_under,x_test,y_test)

[[  58   16]
 [ 372 1049]]
true positive 58
false positive 16
false negative 372
true negative 1049
recall:  0.7837837837837838
precision:  0.13488372093023257
f1_score:  0.23015873015873017
auc:  0.760998155086825


In [ ]:
svmFUN(x_train_under, y_train_under,x_test,y_test)

[[  57   17]
 [ 402 1019]]
true positive 57
false positive 17
false negative 402
true negative 1019
recall:  0.7702702702702703
precision:  0.12418300653594772
f1_score:  0.21388367729831145
auc:  0.7436854518135306


In [ ]:
kN(x_train_under, y_train_under,x_test,y_test)

[[ 48  26]
 [426 995]]
true positive 48
false positive 26
false negative 426
true negative 995
recall:  0.6486486486486487
precision:  0.10126582278481013
f1_score:  0.1751824817518248
auc:  0.6744298837894898


In [ ]:
from imblearn.over_sampling import SMOTE

smoth = SMOTE(random_state=42)

x_train_smoth, y_train_smoth = smoth.fit_resample(x_train, y_train)

In [ ]:
LogisticRegressionFUN(x_train_smoth, y_train_smoth,x_test,y_test)

[[  54   20]
 [ 370 1051]]
true positive 54
false positive 20
false negative 370
true negative 1051
recall:  0.7297297297297297
precision:  0.12735849056603774
f1_score:  0.21686746987951808
auc:  0.7346748578275673


In [ ]:
svmFUN(x_train_smoth, y_train_smoth,x_test,y_test)

[[  55   19]
 [ 394 1027]]
true positive 55
false positive 19
false negative 394
true negative 1027
recall:  0.7432432432432432
precision:  0.12249443207126949
f1_score:  0.21032504780114722
auc:  0.7329868573710938


In [ ]:
from imblearn.under_sampling import NearMiss

nearMiss = NearMiss(version=3)

x_train_nearMiss, y_train_nearMiss = nearMiss.fit_resample(x_train, y_train)

In [ ]:
LogisticRegressionFUN(x_train_nearMiss, y_train_nearMiss,x_test,y_test)

[[ 45  29]
 [687 734]]
true positive 45
false positive 29
false negative 687
true negative 734
recall:  0.6081081081081081
precision:  0.06147540983606557
f1_score:  0.11166253101736973
auc:  0.5623228788253418


In [ ]:
svmFUN(x_train_nearMiss, y_train_nearMiss,x_test,y_test)

[[ 41  33]
 [709 712]]
true positive 41
false positive 33
false negative 709
true negative 712
recall:  0.5540540540540541
precision:  0.05466666666666667
f1_score:  0.09951456310679613
auc:  0.5275548243528538
